package com.kuro.mdp.features.settings.presentation.theme.resource

import androidx.compose.runtime.staticCompositionLocalOf
import org.jetbrains.compose.resources.StringResource
import settings.resources.*

/**
 * Created by: minhthinh.h on 12/25/2024
 *
 * Description:
 */
data class SettingsStrings(
    val settingsTitle: StringResource,
    val mainSettingsTitle: StringResource,
    val mainSettingsThemeTitle: StringResource,
    val topAppBarCategoriesTitle: StringResource,
    val topAppBarTemplatesTitle: StringResource,
    val mainCategoryChooserTitle: StringResource,
    val subCategoryChooserTitle: StringResource,
    val darkThemeTitle: StringResource,
    val lightThemeTitle: StringResource,
    val systemThemeTitle: StringResource,
    val mainSettingsLanguageTitle: StringResource,
    val rusLanguageTitle: StringResource,
    val engLanguageTitle: StringResource,
    val gerLanguageTitle: StringResource,
    val spaLanguageTitle: StringResource,
    val perLanguageTitle: StringResource,
    val freLanguageTitle: StringResource,
    val brazilLanguageTitle: StringResource,
    val turLanguageTitle: StringResource,
    val vieLanguageTitle: StringResource,
    val polLanguageTitle: StringResource,
    val defaultLanguageTitle: StringResource,
    val backIconDesc: StringResource,
    val moreIconDesc: StringResource,
    val resetToDefaultTitle: StringResource,
    val menuIconDesc: StringResource,
    val dataSectionHeader: StringResource,
    val clearDataTitle: StringResource,
    val clearDataButtonTitle: StringResource,
    val clearDataWarning: StringResource,
    val backupDataTitle: StringResource,
    val backupDataButtonTitle: StringResource,
    val restoreDataButtonTitle: StringResource,
    val errorBackupMessage: StringResource,
    val errorBackupFileMessage: StringResource,
    val otherError: StringResource,
    val mainSettingsDynamicColorTitle: StringResource,
    val aboutAppHeader: StringResource,
    val versionCodeTitle: StringResource,
    val versionNameTitle: StringResource,
    val developerTitle: StringResource,
    val licenseTitle: StringResource,
    val githubTitle: StringResource,
    val askQuestionTitle: StringResource,
    val donateTitle: StringResource,
    val copyTitle: StringResource,
    val mainSettingsColorsTitle: StringResource,
    val donateHeader: StringResource,
    val secureSectionHeader: StringResource,
    val secureModeTitle: StringResource,
    val interfaceSectionHeader: StringResource,
    val calendarButtonBehaviorTitle: StringResource,
    val currentDayCalendarBehavior: StringResource,
    val selectDayCalendarBehavior: StringResource
)

val baseSettingsStrings = SettingsStrings(
    settingsTitle = Res.string.settingsTitle,
    mainSettingsTitle = Res.string.mainSettingsTitle,
    mainSettingsThemeTitle = Res.string.mainSettingsThemeTitle,
    topAppBarCategoriesTitle = Res.string.topAppBarCategoriesTitle,
    topAppBarTemplatesTitle = Res.string.topAppBarTemplatesTitle,
    mainCategoryChooserTitle = Res.string.mainCategoryChooserTitle,
    subCategoryChooserTitle = Res.string.subCategoryChooserTitle,
    darkThemeTitle = Res.string.darkThemeTitle,
    lightThemeTitle = Res.string.lightThemeTitle,
    systemThemeTitle = Res.string.systemThemeTitle,
    mainSettingsLanguageTitle = Res.string.mainSettingsLanguageTitle,
    rusLanguageTitle = Res.string.rusLanguageTitle,
    engLanguageTitle = Res.string.engLanguageTitle,
    gerLanguageTitle = Res.string.gerLanguageTitle,
    spaLanguageTitle = Res.string.spaLanguageTitle,
    perLanguageTitle = Res.string.perLanguageTitle,
    freLanguageTitle = Res.string.freLanguageTitle,
    brazilLanguageTitle = Res.string.braporLanguageTitle,
    turLanguageTitle = Res.string.turLanguageTitle,
    vieLanguageTitle = Res.string.vieLanguageTitle,
    polLanguageTitle = Res.string.polLanguageTitle,
    defaultLanguageTitle = Res.string.defaultLanguageTitle,
    backIconDesc = Res.string.backIconDesc,
    moreIconDesc = Res.string.moreIconDesc,
    resetToDefaultTitle = Res.string.resetToDefaultTitle,
    menuIconDesc = Res.string.menuIconDesc,
    dataSectionHeader = Res.string.dataSectionHeader,
    clearDataTitle = Res.string.clearDataTitle,
    clearDataButtonTitle = Res.string.clearDataButtonTitle,
    clearDataWarning = Res.string.clearDataWarning,
    backupDataTitle = Res.string.backupDataTitle,
    backupDataButtonTitle = Res.string.backupDataTitle,
    restoreDataButtonTitle = Res.string.restoreDataButtonTitle,
    errorBackupMessage = Res.string.errorBackupMessage,
    errorBackupFileMessage = Res.string.errorBackupFileMessage,
    otherError = Res.string.otherError,
    mainSettingsDynamicColorTitle = Res.string.mainSettingsDynamicColorTitle,
    aboutAppHeader = Res.string.aboutAppHeader,
    versionCodeTitle = Res.string.versionCodeTitle,
    versionNameTitle = Res.string.versionNameTitle,
    developerTitle = Res.string.developerTitle,
    licenseTitle = Res.string.licenseTitle,
    githubTitle = Res.string.githubTitle,
    askQuestionTitle = Res.string.askQuestionTitle,
    donateTitle = Res.string.donateTitle,
    copyTitle = Res.string.copyTitle,
    mainSettingsColorsTitle = Res.string.mainSettingsColorsTitle,
    donateHeader = Res.string.donateHeader,
    secureSectionHeader = Res.string.secureSectionHeader,
    secureModeTitle = Res.string.secureModeTitle,
    interfaceSectionHeader = Res.string.interfaceSectionHeader,
    calendarButtonBehaviorTitle = Res.string.calendarButtonBehaviorTitle,
    currentDayCalendarBehavior = Res.string.currentDayCalendarBehavior,
    selectDayCalendarBehavior = Res.string.selectDayCalendarBehavior
)

internal val LocalSettingsStrings = staticCompositionLocalOf<SettingsStrings> {
    error("Settings Strings is not provided")
}

internal fun fetchSettingsStrings() = baseSettingsStrings